### ISSUE TITLE
Help doesn't show all possible arguments

### ISSUE THREAD

**Issue by de-sh** [parseablehq/parseable#1036]
The binary can take a lot of arguments/env variables, but currently, the following is the output of the call to `parseable --help`
```sh
Parseable v1.6.3

Cloud Native, log analytics platform for modern applications.
Join the community at https://logg.ing/community.

Commands:
  local-store  Start Parseable with a drive as storage
  s3-store     Start Parseable with S3 or compatible as storage
  blob-store   Start Parseable with Azure Blob storage
  help         Print this message or the help of the given subcommand(s)

Options:
  -h, --help     Print help
  -V, --version  Print version
```

No listing of possible commandline arguments is shown as would be expected from a commandline utility.

**Comment by TwistingTwists** [comment]
Please assign this to me. :)

**Comment by TwistingTwists** [comment]
https://asciinema.org/a/dvfmqCQzG1HqzeX5uRRYgFaRG

the cli follow standard clap behaviour. of showing commands and nested commands, one level at a time.

**Comment by de-sh** [comment]
@Anirudhxx the main idea behind this PR was to point out the available options at the global level, the idea is that we should print the common options for all subcommands, stuff like setting up kafka connector, hottier etc. But now that I think about it from a user perspective the following addition could be good enough to point the usage of each command:

```
parseable [command] [options..]
```
