### ISSUE TITLE
websocket api

### ISSUE THREAD

**Issue by tianbaoluo** [parseablehq/parseable#115]
Could you provide WebSocket API so user can post log continuously?

**Comment by nitisht** [comment]
@tianbaoluo can you explain your use case a little better. Isn't it possible to send logs via HTTP API continuously for you..?

**Comment by tianbaoluo** [comment]
@nitisht Thank you for your reply.
I need to continuously store data to s3, but estimated data generation speed is faster than HTTP request processing speed. I hope I can establish a WebSocket and then keep POSTing data to speed up the speed.

**Comment by nitisht** [comment]
Thanks @tianbaoluo this is useful. If I may ask further, 

> estimated data generation speed is faster than HTTP request processing speed.

Would you mind sharing this number? FYI, Parseable should be able to ingest data at much faster rate as compared to S3 because of our builtin stage and forward mechanism. 

Feel free to join us on Slack https://launchpass.com/parseable for quicker discussion

**Comment by tianbaoluo** [comment]
@nitisht Thank you for your reply.
Actually, we want to use parseable to store order book data, sometimes there are 500～1000 order books per second.

**Comment by nitisht** [comment]
>  sometimes there are 500～1000 order books per second, or more than this.

Parseable is able to ingest logs are this volume with 4 cpu cores in our internal testing. Would you try this with a VM in your environment?

**Comment by tianbaoluo** [comment]
> > sometimes there are 500～1000 order books per second, or more than this.
> 
> Parseable is able to ingest logs are this volume with 4 cpu cores in our internal testing. Would you try this with a VM in your environment?

Thank you, I would try.

**Comment by nitisht** [comment]
Thanks, please let us know how it goes.

**Comment by nitisht** [comment]
@tianbaoluo curios how did it go for you?

**Comment by nitisht** [comment]
Closing this due to no response.
