### ISSUE TITLE
[Integration] Grafana datasource

### ISSUE THREAD

**Issue by denisgolius** [parseablehq/parseable#116]
Could you add own datasource to use `parseable` as datasource in Grafana as it done for [Grafana Loki](https://grafana.com/grafana/plugins/loki/)/[Elasticsearch](https://grafana.com/grafana/plugins/elasticsearch/)/[Clickhouse](https://grafana.com/grafana/plugins/?search=Clickhouse)?

**Comment by nitisht** [comment]
Hey, @denisgolius thank you for the issue. Yes, this has been on our radar and we're actively working on this. We'll let you know once this is done. cc @AdheipSingh

**Comment by nitisht** [comment]
The datasource plugin is available here https://github.com/parseablehq/parseable-datasource. We'll add detailed docs and also add it to the Grafana community plugin list

**Comment by denisgolius** [comment]
> The datasource plugin is available here https://github.com/parseablehq/parseable-datasource. We'll add detailed docs and also add it to the Grafana community plugin list

Cool, thanks you!
