### ISSUE TITLE
Document FluentBit with Parseable

### ISSUE THREAD

**Issue by nitisht** [parseablehq/parseable#126]
Parseable is compatible with FluentBit HTTP Output: https://docs.fluentbit.io/manual/pipeline/outputs/http

We need to document step by step guide on setting up FluentBit with Parseable

**Comment by akebu6** [comment]
In order to work on this, we have to read the documentation on the link shared correct?

**Comment by nitisht** [comment]
Yes, you can start with the documentation in the link and feel free to ask any questions you might have..

**Comment by akebu6** [comment]
Awesome, may I have it assigned to me then?

**Comment by nitisht** [comment]
done! looking forward to your work @akebu6 . Thank you for contributing to Parseable

**Comment by akebu6** [comment]
@nitisht where will the guide for this be placed? is there a particular folder or I should just create the document and place it anywhere?

**Comment by nitisht** [comment]
You can create a docs directory and add the file there

**Comment by akebu6** [comment]
Got it

**Comment by nitisht** [comment]
This is done now https://www.parseable.io/docs/log-agents/fluentbit
