### ISSUE TITLE
Populate the demo instance with large amounts of data

### ISSUE THREAD

**Issue by knadh** [parseablehq/parseable#144]
Hi. It'd be nice for the demo (demo.parseable.io) to be preloaded with large amounts of data to get a good sense of how it functions. I was playing around with it and could only see two events logged in the last 6 months.

If it helps, [here](https://demo.listmonk.app/admin/campaigns/analytics?id=2), I've a cron job that generates and populates dummy, but current data every day. A simple approach like that would do.

**Comment by nitisht** [comment]
Hey @knadh thanks for the issue. Let me set this up, today.

**Comment by nitisht** [comment]
I have added a cron job for this now.

**Comment by knadh** [comment]
Thanks!
