### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by nitisht** [parseablehq/parseable#145]
In case a stream is empty, i.e. has no log data yet, the Query API responds with `Failed to execute query due to err: missing record batch`. 

This is confusing and might not make sense to end user. This error should be changed to say `No log entries found in log stream xxx`. Also the status code should be `404`.

**Comment by kmartin62** [comment]
I tried to find where this error `Failed to execute query due to err: missing record batch` is placed but couldn't find it. Can you point it for me?

**Comment by nitisht** [comment]
We'll get back in a bit @kmartin62

**Comment by trueleo** [comment]
@kmartin62 Sorry for inconvenience. After one of my recent PR this has changed to `Bad request: Error parsing query: Stream is not initialized yet. Post an event first.`. This is fine but we actually want more readable error than this. 

Error types for now compose upwards the call stack. The type is `QueryErrro(ParseError(QueryValidationError))`

For this specific issue, main problem arises from coupling of schema with Query. @nitisht I will open a new issue for this.

**Comment by nitisht** [comment]
> Error types for now compose upwards the call stack. The type is QueryError::Parse(ParseError::Validation(QueryValidationError))

Can you link to this in the repo.

**Comment by trueleo** [comment]
> > Error types for now compose upwards the call stack. The type is QueryError::Parse(ParseError::Validation(QueryValidationError))
> 
> Can you link to this in the repo.
[here](https://github.com/parseablehq/parseable/blob/dd24e091eaa1399384a1171b6e9d34143eb1b3fb/server/src/validator.rs#L155-L157) 
also mentioned in #147

**Comment by nitisht** [comment]
closing this as duplicate of #147
