### ISSUE TITLE
[Document] How to send logs to Parseable from a Rust application

### ISSUE THREAD

**Issue by nitisht** [parseablehq/parseable#146]
Parseable website has docs on how to directly send logs from Go, Python, Java, JS etc. Ref: https://www.parseable.io/docs/log-ingestion/applications/go

We need to add docs on how to directly sends logs from a Rust application. 

Please send the PR to parseablehq/parseable repo and we'll add it to the website.

**Comment by nitisht** [comment]
@123vivekr would you take this up as well?

**Comment by 123vivekr** [comment]
Yes 👍

**Comment by nitisht** [comment]
Fixed by #196
