### ISSUE TITLE
Decouple metadata lookup from query validation 

### ISSUE THREAD

**Issue by trueleo** [parseablehq/parseable#147]
When building a query from request, parsing validation [looks up metadata](https://github.com/parseablehq/parseable/blob/dd24e091eaa1399384a1171b6e9d34143eb1b3fb/server/src/validator.rs#L155-L157) to get schema for Query struct. Validation should be self contained and should not lookup anything from metadata.

**Comment by nitisht** [comment]
how about this @trueleo ?

**Comment by trueleo** [comment]
@nitisht , not relevant as well but we still need better error messages on some APIs. You can close this
