### ISSUE TITLE
Document Syslog-ng log forwarding to Parseable

### ISSUE THREAD

**Issue by nitisht** [parseablehq/parseable#150]
Syslog-ng supports sending logs to http endpoints as per the docs here: https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.24/administration-guide/37#TOPIC-1298006

We need to document how to fetch logs in json format and forward logs to Parseable

**Comment by sakti** [comment]
@nitisht I also want to take this issue.

**Comment by nitisht** [comment]
Thanks @sakti , moving this to you
