### ISSUE TITLE
Add support for multi-arch Docker images

### ISSUE THREAD

**Issue by nitisht** [parseablehq/parseable#163]
We need to add support for multi-arch images 

https://docs.docker.com/desktop/extensions-sdk/extensions/multi-arch/

**Comment by nitisht** [comment]
@Mayon-Francis are you working on this still?

**Comment by Theofrid** [comment]
I would work on this issue. So, could you please assign this to me?

**Comment by Theofrid** [comment]
I would like to work on this issue. So, could you please assign this to me?

**Comment by nitisht** [comment]
Hi @Theofrid sure. Just to be clear, the issue regarding support for multi-arch images for the Parseable Docker Image

**Comment by hyperreal64** [comment]
> I would like to work on this issue. So, could you please assign this to me?

Any progress on this yet? :-)

**Comment by Theofrid** [comment]
Yeah, I am still working on it. It took me a little bit of time to
understand the issue, but I am making progress.

**Comment by Theofrid** [comment]
I have a doubt. The alpine docker image variant only support two architectures, that is amd64 and arm64/v8. So, should I have to switch to other docker image variants like latest or slim-buster in order to implement support for other architectures too?

**Comment by nitisht** [comment]
Hey @Theofrid for now, if we can support amd64 and arm64 for standard OS (windows, macOS, Linux) I think we're good.

**Comment by Theofrid** [comment]
~ + docker buildx build --platform linux/amd64 --tag parseable/rust:1.65-alpine3.16 --push .

I ran this command and there was a  compiling error and I am not sure what to do with this.

![compile_error](https://user-images.githubusercontent.com/118801625/204979082-8f14a67f-e770-45cc-a304-47541b3cdc95.png)

**Comment by nitisht** [comment]
cc @trueleo

**Comment by nitisht** [comment]
also @Theofrid would you mind joining our slack we can discuss and see how to fix this

**Comment by trueleo** [comment]
@Theofrid I am not sure why this is happening on 1.65 .. I will check Minimum Support Rust Version for zstd and packages depending on it.

**Comment by syepes** [comment]
@nitisht | @trueleo What platforms would you guys like to target?
In one of my projects I managed to have cross compiled images but it was not the easiest thing, also not all dependencies work on all platforms :-(

Hope this could serve you as a reference:
https://github.com/syepes/sio2prom/blob/a4c751b366e30969dc13e04bd4f97dda501f66b3/.github/workflows/release.yml#L15

**Comment by nitisht** [comment]
Hey @syepes I was thinking of atleast `linux/arm64` for now. The workflow file looks a good idea, let me try this out today. Thanks for the pointer!

**Comment by teddybee** [comment]
It would be good to have ARM64 images, there are lots of servers now.

**Comment by nitisht** [comment]
This is great @Eshanatnight , can you send a PR to the github actions so this image is automatically built and pushed to dockerhub.
