### ISSUE TITLE
Show git sermver in banner  

### ISSUE THREAD

**Issue by trueleo** [parseablehq/parseable#165]
[vergen]( https://crates.io/crates/vergen) crate sets environment variable `VERGEN_GIT_SEMVER` at build time which looks like this `5.0.0-2-gf49246c`. Banner should show this version and possibly some other information if Parseable is ran from a git environment where HEAD is not on version tagged commit. Otherwise it should show semver like `5.0.0` for the release build done on tagged commit

**Comment by nitisht** [comment]
@123vivekr would you take this up ?

**Comment by 123vivekr** [comment]
Yes, I'll take this up 👍
