### ISSUE TITLE
[feature] Support schema evolution in a given stream

### ISSUE THREAD

**Issue by nitisht** [parseablehq/parseable#195]
As applications evolve, the log events they generate evolve as well. It would be very useful for Parseable server allow schema evolution of a given stream as source applications evolve. This is also reported a as a common issue with ES. 

This change would

- further reduce the burden on the user/operator to manage schema
- ensure application's entire life cycle log event data resides on a single Parseable stream, allowing easier analysis
- remove fragmentation of log data across streams

**Comment by 123vivekr** [comment]
Is this being worked on currently?
