### ISSUE TITLE
Parseable with digital Ocean Spaces

### ISSUE THREAD

**Issue by izzie88** [parseablehq/parseable#232]
Hello,

I wanted to find out if we can use parseable with digital ocean spaces(object storage) or it is strictly AWS S3 only.

**Comment by nitisht** [comment]
Hey @izzie88 yes, you can use DO Spaces with Parseable. In fact Parseable demo server (https://demo.parseable.io) was based on DO Spaces for a while. 

It should work fine and please do let us know if it doesn’t we’ll fix it asap.

**Comment by nitisht** [comment]
Closing this as answered

**Comment by izzie88** [comment]
Hello Nitish,

I just deployed using Spaces and this log was thrown back at me.

thread 'main' panicked at 'Could not start because the bucket doesn't
exist. Please ensure bucket parseable exists on
https://parseable.fra1.digitaloceanspaces.com', server/src/option.rs:88:60
stack backtrace:

**Comment by izzie88** [comment]
Hello Nitisht,

please see below the stack trace:



   9:     0x7f5950b4040f - std::panicking::default_hook::hf5508b7bdf3babed
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:314:9
  10:     0x7f5950b40dca - std::panicking::rust_panic_with_hook::h8ac2ad414f2a80a8
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:698:17
  11:     0x7f5950b40cc7 - std::panicking::begin_panic_handler::{{closure}}::h6806472e4abb4c1b
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:588:13
  12:     0x7f5950b3f39c - std::sys_common::backtrace::__rust_end_short_backtrace::h0c0f5202fe96986e
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x7f5950b409e2 - rust_begin_unwind
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
  14:     0x7f594f09f183 - core::panicking::panic_fmt::h6bdb18f09e76240c
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
  15:     0x7f594f2d99aa - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha95afcb1b1e0afc9
  16:     0x7f594f239323 - std::thread::local::LocalKey<T>::with::h73cac4a47a2d94ca
  17:     0x7f594f1bfb87 - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::h25825aa29d17b91f
  18:     0x7f594f2c9614 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h6cd9503e0a45c0cf
  19:     0x7f594f239056 - std::thread::local::LocalKey<T>::with::h15b56db1cebd8b01
  20:     0x7f594f118334 - tokio::runtime::basic_scheduler::Context::enter::hed97c63345e44962
  21:     0x7f594f1b253b - tokio::macros::scoped_tls::ScopedKey<T>::set::hf2bb9540f3a100c3
  22:     0x7f594f117a97 - tokio::runtime::basic_scheduler::BasicScheduler::block_on::h4a8ed891ab3f13d8
  23:     0x7f594f139f33 - tokio::runtime::Runtime::block_on::h0a8137d808bee1a8
  24:     0x7f594f0d1e90 - parseable::main::h913953a71b47dac6
  25:     0x7f594f1fe613 - std::sys_common::backtrace::__rust_begin_short_backtrace::h60e4f6be626c4356
  26:     0x7f594f254db9 - std::rt::lang_start::{{closure}}::h9aa16323980a3af8
  27:     0x7f5950b31ec2 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h08229953798ceb9c
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:283:13
  28:     0x7f5950b31ec2 - std::panicking::try::do_call::h85f860db39727e24
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
  29:     0x7f5950b31ec2 - std::panicking::try::h81d98391c5fe7aa5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
  30:     0x7f5950b31ec2 - std::panic::catch_unwind::hf0da87b0c0419439
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
  31:     0x7f5950b31ec2 - std::rt::lang_start_internal::{{closure}}::h8fdd0caa04652723
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:148:48
  32:     0x7f5950b31ec2 - std::panicking::try::do_call::h610b603febbce952
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
  33:     0x7f5950b31ec2 - std::panicking::try::h1e387bee0c3d3c28
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
  34:     0x7f5950b31ec2 - std::panic::catch_unwind::h9f8125a9743b85d4
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
  35:     0x7f5950b31ec2 - std::rt::lang_start_internal::h829c8136aeac5647
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:148:20
  36:     0x7f594f0d1ef8 - main

**Comment by nitisht** [comment]
Thanks @izzie88 checking now. Just to confirm, does the bucket `parseable` exist?

**Comment by izzie88** [comment]
Yes, that is correct.

We have figured it out on our end.

The URL should be set to https://fra1.digitaloceanspaces.com instead of
https://parseable.fra1.digitaloceanspaces.com

**Comment by nitisht** [comment]
awesome! please let us know here if something else comes up.
