### ISSUE TITLE
[feature] Add local file system support

### ISSUE THREAD

**Issue by aaronjheng** [parseablehq/parseable#233]
When trying out parseable or doing local development, it would be good to support local FS storage instead of object storage.

**Comment by nitisht** [comment]
hey @aaronjheng thank you for the issue. We do agree, and already added this support with https://github.com/parseablehq/parseable/pull/217. This will be available in the next release (we’re aiming for the release next week)

**Comment by nitisht** [comment]
closing this as fixed by https://github.com/parseablehq/parseable/pull/217
