### ISSUE TITLE
Parseable Service goes into panic randomly

### ISSUE THREAD

**Issue by imagdy83** [parseablehq/parseable#258]
Dashboard doesn't show any data
journalctl -u parseable shows the following

parseable[3597327]: thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', server/src/storage.rs:352:13

parseable[3597327]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', server/src/storage.rs:138:61

**Comment by nitisht** [comment]
Thanks @imagdy83 we'll look into this quickly. What is the server version here?

**Comment by imagdy83** [comment]
Current Version: 0.0.7

**Comment by trueleo** [comment]
@imagdy83 Hello, thanks for reaching out. I will check why it happened but meanwhile can you restart parseable and wait for minute or two then check following 
* there should be no data in the data directory 
* any data that failed to upload previously should upload to s3

**Comment by imagdy83** [comment]
@trueleo 
Can you provide the steps to update from 0.0.7 to 0.1.0

**Comment by trueleo** [comment]
@imagdy83 

> What do you mean there shouldn't ne data in the data directory? there is a folder for each stream we've created
there should be a directory called `data` ... it is created in the current directory relative to where parseable executable is

**Comment by trueleo** [comment]
> @trueleo Can you provide the steps to update from 0.0.7 to 0.1.0

If you check 0.1 release notes we do not "support" migration from <0.0.8 to 0.1. But it is not technically impossible, If you cannot do a clean setup and want to migrate we are happy to help on Slack. https://launchpass.com/parseable

I will ping you here if I find it possible to reuse the bucket you created on 0.0.7 for 0.1

**Comment by imagdy83** [comment]
the service file is corrupt
can you provide a service file for linux please

**Comment by imagdy83** [comment]
parseable.service: Starting requested but asserts

**Comment by nitisht** [comment]
The command to start the server has changed (need to add `s3-store` after parseable), this is the new service file https://github.com/parseablehq/parseable/blob/main/systemd/parseable.s3.service

**Comment by trueleo** [comment]
@imagdy83 If you want to use your existing bucket (which was created on v0.0.7) you will have to rename a file on s3.   `stream_name/.parseable.json` to `stream_name/.stream.json` . You can do this through s3 move command or by downloading file and re uploading under new name.

**Comment by imagdy83** [comment]
So far it has not paniced, I'll keep you posted
thanks

**Comment by imagdy83** [comment]
Good Morning we've hit a ton of errors looking like these
parseable[3612606]: thread 'actix-rt|system:0|arbiter:0' pani

parseable[3612606]: thread 'actix-rt|system:0|arbiter:0' panicked at 'no poisoning: PoisonError { .. }', server/src/query/table_provider.rs:57:70

**Comment by trueleo** [comment]
@imagdy83 Can you tell me about you setup. How did you set parseable up and what your typical usecase is like.

**Comment by imagdy83** [comment]
- We've got several sources with logs
- Each of the sources forwards their logs to a syslog-ng instance that's deployed on the same server that parseable is installed on
- Syslog-ng has one of it's destinations as the parseable server and there is another log forwarder on a different source that forwards directly to parseable
- logs naturally get uploaded to s3 in the process

**Comment by nitisht** [comment]
@imagdy83 would you mind getting on a short call to address this? The use case is exactly the kind we're looking at and we'd love to fix this asap for you.

Also have you upgraded to v0.1.0 already?

**Comment by imagdy83** [comment]
Sounds good, don't mind
yes we're at v0.1.0 at the moment

**Comment by nitisht** [comment]
okay, I am at nitish@parseable.io , please drop a note and we'll schedule the call

**Comment by imagdy83** [comment]
sent you an email
