### ISSUE TITLE
Make the image fit for OpenShift 

### ISSUE THREAD

**Issue by rschumm** [parseablehq/parseable#267]
running Parseable on OpenShift causes the Pod to crash while startup: 

`error: Invalid value '/parseable/staging' for '--local-staging-path <DIR>': Permission denied (os error 13)
`

probably the image is not fit for openshift: 

https://github.com/parseablehq/parseable/blob/26d476b286bfe2c850e3324880d2d7c2ecacb164/Dockerfile#L42

--> https://docs.openshift.com/container-platform/4.11/openshift_images/create-images.html#images-create-guide-openshift_create-images

probably the docker file needs a fix.

**Comment by nitisht** [comment]
Thanks @rschumm . Let me try this and get back

**Comment by nitisht** [comment]
@rschumm I believe https://github.com/parseablehq/parseable/pull/269 should have fixed your issue.

**Comment by nitisht** [comment]
Closing this as fixed by #269. Thank you for the confirmation @rschumm

**Comment by rschumm** [comment]
I forgot to confirm here (did only in the slack channel) - yes, this fix worked as intended! Thanks!

**Comment by nitisht** [comment]
Thanks @rschumm
