### ISSUE TITLE
[Feature] AlertManager support as TargetType

### ISSUE THREAD

**Issue by syepes** [parseablehq/parseable#288]
It would be great and very useful if we added support of [Alertmanager](https://github.com/prometheus/alertmanager) as a new TargetType. This would allow alerts to be integrated into existing tooling and ecosystems that support AlertManager.

Other 3th party tooling like the vmalert have done the integration: 
https://github.com/VictoriaMetrics/VictoriaMetrics/tree/cluster/app/vmalert/notifier

**Comment by nitisht** [comment]
Thanks @syepes we’ll take this up on priority
