### ISSUE TITLE
Additional labels for alertmanager target types in log alert spec

### ISSUE THREAD

**Issue by nitisht** [parseablehq/parseable#311]
We could also add some additional `labels` to add more context from where the alert is coming from.

https://github.com/parseablehq/parseable/blob/c15cdd1cf00888a0e33d852e866d1f5425e96b1f/server/src/alerts/target.rs#L261

Suggested additional labels: 
```
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config

__address__ = config.parseable.address
__scheme__ = config.parseable.get_scheme()
__alerts_path__ = /api/v1/logstream/{{stream_name}}/alert

__meta_parseable_deployment_id = StorageMetadata.deployment_id
__meta_parseable_version = StorageMetadata.version
__meta_parseable_mode = StorageMetadata.mode
__meta_parseable_alert_rule_type = "column"
__meta_parseable_alert_rule_config_column = "status"
__meta_parseable_alert_rule_config_operator = "notEqualTo"
__meta_parseable_alert_rule_config_repeats = 2
__meta_parseable_alert_rule_config_value = 500
```

_Originally posted by @syepes in https://github.com/parseablehq/parseable/issues/306#issuecomment-1442498884_

**Comment by nitisht** [comment]
@syepes how about clubbing the whole alert reason into a single label, like so?

```
__meta_parseable_alert_reason = "status not equal to 500, 2 times"
```

**Comment by syepes** [comment]
> @syepes how about clubbing the whole alert reason into a single label, like so?
> 
> ```
> __meta_parseable_alert_reason = "status not equal to 500, 2 times"
> ```

That also would work but also having the `__meta_parseable_alert_rule_type` to know the type

**Comment by nitisht** [comment]
Thanks @syepes makes sense. We looked at [templating in alertmanager](https://prometheus.io/docs/alerting/latest/notification_examples/) and now we agree on your initial proposal of separate labels for each rule field. 

This will allow users to template their rules and notifications exactly how they need it. Much more powerful this way.

**Comment by syepes** [comment]
No problem, that was the initial idea to not have to re-parse the labels.

**Comment by syepes** [comment]
@nitisht 
This is now working pretty good, the only missing label would be the `instance = config.parseable.address`, so we can go back to the parseable instance that generated this alert:

![CleanShot 2023-02-27 at 4 11 58](https://user-images.githubusercontent.com/333081/221602834-6b158e43-6bc7-481d-a178-1c3c06270294.png)

**Comment by nitisht** [comment]
Thanks @syepes . PR looking great - thank you for the contribution as always 👍🏽
