### ISSUE TITLE
Grafana datasource plugin doesn't show as an eligible source for the Logs panel

### ISSUE THREAD

**Issue by netcho** [parseablehq/parseable#324]
Installing the latest Parseable Grafana datasource plugin does not show the created datasource as an available option for a Logs panel.

Grafana version: v9.3.2
Grafana Parseable datasource plugin: 1.0.1

**Comment by nitisht** [comment]
Thanks @netcho we'll take a look soon.

**Comment by nitisht** [comment]
Fix will be available in 1.0.2
