### ISSUE TITLE
Feature Request: Provision to send custom messages with log content as alerts using Alert API.

### ISSUE THREAD

**Issue by ARK-ASWINRAJ** [parseablehq/parseable#331]
**The context**

I'm using parseable for logging in with Winston logger and sending alerts based on custom rules to a slack channel. This is super helpful. But still, I can only send custom strings as message `content` for alerts. Actually, I wanted to send the 'log content' (including stack trace) or the value in a specific column in a log to slack. But couldn't find a way to do the same.
`{
        version: "v1",
        alerts: [
            {
                name: "Crash Alert",
                message: "Server Crashed",
                rule: {
                    type: "column",
                    config: {
                        column: "status",
                        operator: "=",
                        repeats: 3,
                        value: 500,
                    },
                },
                targets: [
                    {
                        type: "slack",
                        config: {
                            url: slackUrl
                        },
                        repeat: "1m",
                    },
                ],
            },
        ],
    };`

**What would be great ?**

If I can do something like this-:
`{
        version: "v1",
        alerts: [
            {
                name: "Crash Alert",
                message: "Server Crashed: {log_entry.message}",
                rule: {
                    type: "column",
                    config: {
                        column: "status",
                        operator: "=",
                        repeats: 3,
                        value: 500;
                    },
                },
                targets: [
                    {
                        type: "slack",
                        config: {
                            url: slackUrl,
                        },
                        repeat: "1m",
                    },
                ],
            },
        ],
    };`

If there's a provision to send custom fields like (`{log_entry.message}`) in logs along with or within 'message' as a payload for alerts, that would be perfect.

**Comment by nitisht** [comment]
Thanks @ARK-ASWINRAJ we'll take a look

**Comment by Rodelkoenig** [comment]
@nitisht great feature! I think a mention or sample in official docs (https://www.parseable.io/docs/alerts) would be helpful for others, found it only by accident.

**Comment by nitisht** [comment]
Thanks @Rodelkoenig we’ll add it in the docs

**Comment by jybleau** [comment]
How do we use this feature?
i can create an alert with `"message": "Error: {label} {message}",`
The Alert Manager validates the `label` and `message` column.

But when I trigger an alert, the message returned is still: `"message": "Error: {label} {message}",`
values are not replaced.

**Comment by jybleau** [comment]
> logging in with Winston logger

@ARK-ASWINRAJ I've published a Winston transport https://www.npmjs.com/package/parseable-winston
was wondering if you could have a look? It uses a buffer to send ingestion in batch

If it's worth it, I could suggest to add a reference to the documentation, if the maintainers think it's a valuable addition.

_btw: struggling to use this custom message feature correctly._

**Comment by nitisht** [comment]
Thanks for reporting @jybleau we'll add this in docs in detail. Reopening the issue to track.
