### ISSUE TITLE
Demo.parseable.io credentials

### ISSUE THREAD

**Issue by peterinfra** [parseablehq/parseable#367]
the demo website https://demo.parseable.io/ credentials are unknown. Can you link it to the documentation ?

**Comment by nitisht** [comment]
Credentials are `admin` and `admin`. 

![image](https://user-images.githubusercontent.com/5156139/232694350-8d5f684c-94ff-42c1-8d0c-41b744a24c7f.png)

**Comment by nitisht** [comment]
We'll make this more obvious, I see that it is easy to miss the creds

**Comment by peterinfra** [comment]
Thanks I can login and view it. These credentials are not available on the main website (https://www.parseable.io/)
