### ISSUE TITLE
Unified Backend result type for all the function calls 

### ISSUE THREAD

**Issue by artech-git** [parseablehq/parseable#374]
This is purely based upon some understanding after looking into the codebase, I think having a universal custom Error type is very useful
which can include the capability of backtracing and managing the error types from one type itself 

for example
```rust
async fn some_func(..) -> Result<impl Responder, StreamError>
```

could be used instead with

```rust
type BackendResult<T> = std::result::Result<T, BackendError>;
.
.
async fn some_func(..) -> BackendResult<impl Responder>
.
.
#[this_error]
pub enum BackendError {
  ErrorType1,
  ErrorType2,
  StreamError,
}
```

we can then include our Error type directly inside the Enum (BackendError), this one is just a abstract concept but need some inputs whether this approach to handle error would be useful ?

**Comment by nitisht** [comment]
Hey @artech-git thank you for the issues - do you mind joining our Slack, we can discuss and move on this quickly

**Comment by artech-git** [comment]
> Hey @artech-git thank you for the issue - do you mind joining our Slack, we can discuss and move on this quickly. https://launchpass.com/parseable

sure 😊

**Comment by nitisht** [comment]
related to #2 . Closing #2 in favour of this issue.

**Comment by trueleo** [comment]
>  having a universal custom Error type is very useful

It is convenient for sure when you can just return error from anywhere 

But the problem i see with universal error is that they are too opaque sometimes. For example a common error that happens is `serde_json::Error`, this can happen for any reason at any place. Maybe deserialization failed on first time bytes were deserialized in to or maybe it happens later in the event handling module. So we gonna be attaching context to it anyways. 

Using one error type for each major module seems like a good way to go for now.

Here is what i think about current error handling situation
* The display for error needs to be adjusted and should contain more context for **_users_**  
* If we replace everything with universal error types then we need to add more context for **us** (using tracing).

I have not fully tried compared `thiserror` with `snafu` but snafu seems a bit better overall. If we shift from one way or error to other then i will probably try to utilize that .

**Comment by artech-git** [comment]
totally agreed opaqueness caused through this abstraction is present, to counter what we can attempt to use probably could be attach a backtrace and location within our BackendError kind Like this

```rust
pub type BackendServerResult<T> = std::result::Result<T, BackendServerError>;

#[derive(Debug,)]
pub struct BackendServerError {
    location: std::panic::Location,
    backtrace: std::backtrace::Backtrace,
    error: ServerErrors,
}

impl from<E> for BackendServerError 
where E: Into<ServerErrors> 
{
    #[trace_caller]
    fn from(value: E) -> Self {
     ...
    }
}


impl std::fmt::Display for BackendServerError {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result<(), std::fmt::Error> {
        let err = self.error.to_str();
        write!(f, "BackendServerError: {err}")
    }
}

impl std::error::Error for BackendServerError {}


#[derive(Error, Debug)]
enum ServerErrors {
  ....
}
```

**Comment by trueleo** [comment]
@artech-git Sorry, i just needed bit clarification on this issue. Do you want to categorize all module errors into BackendError and ClientError or you mean that we should replace all module level error with Backenderror. Later situation is what i was referring to.

**Comment by artech-git** [comment]
It's fine .. actually my approach was the first one 

- create a separate module (in the src folder) for handling errors globally
-  and to substitute the error types in each module previously present with this type 

also please have a look on the main channel of slack I have briefly explained about the categorization of the error types for both categories of errors (server and client error)

**Comment by nitisht** [comment]
Closing this for now as we're not taking it up
