### ISSUE TITLE
Permission denied (os error 13) while trying to run Parseable.

### ISSUE THREAD

**Issue by Allyedge** [parseablehq/parseable#377]
Hi everyone.

I am running a slightly modified version of the `docker run` command provided by the documentation, and I did try running the exact snippet there as well but both resulted in the same error.

The command I am running:

```sh
docker run -p 8000:8000 --name parseable \
-v $HOME/docker/volumes/parseable:/parseable/data \
-v $HOME/docker/volumes/parseable:/parseable/staging \
-e P_FS_DIR=/parseable/data \
-e P_STAGING_DIR=/parseable/staging \
parseable/parseable:latest \
parseable local-store
```

The container gets created, but then crashes with this error.

```
Error: IO Error: Permission denied (os error 13)

Caused by:
    Permission denied (os error 13)
```

I guess this is some Rust related error, but I can't tell for sure.

How can I fix this?

Thanks!

**Comment by nitisht** [comment]
Thanks @Allyedge let me try this and get back

**Comment by nitisht** [comment]
Hey @Allyedge I just tried this, can you fix two things in the command

1. Make sure the user running the docker run command has r+w access to the directory `$HOME/docker/volumes/parseable`.
2. Use separate directories for data and staging like this

```
docker run -p 8000:8000 --name parseable \
-v $HOME/docker/volumes/parseable/data:/parseable/data \
-v $HOME/docker/volumes/parseable/staging:/parseable/staging \
-e P_FS_DIR=/parseable/data \
-e P_STAGING_DIR=/parseable/staging \
parseable/parseable:latest \
parseable local-store
```

**Comment by Allyedge** [comment]
Thanks for the answer @nitisht, I confirmed that the user does indeed have access to the directory, and running the updated command also did not change anything.

I am still getting the same error, not sure what exactly is wrong.

The error is coming from the Docker container, though, not my machine itself.

**Comment by nitisht** [comment]
What is the OS here @Allyedge ? Linux / macOS?

**Comment by Allyedge** [comment]
> What is the OS here @Allyedge ? Linux / macOS?

I am using WSL 2 on Windows.

**Comment by Allyedge** [comment]
Solved it on Slack, `/tmp` directory worked while the `$HOME/docker/volumes` failed, I guess it is a WSL related issue.

Thanks for the help!

**Comment by nitisht** [comment]
Thanks @Allyedge 👍🏽

**Comment by vytas7** [comment]
I'm getting the same error on Linux, both when running Docker as root and rootless, when trying to use `/tmp`: `-v /tmp/parseable/data:/parseable/data -v /tmp/parseable/staging:/parseable/staging`.

Running without any volumes works fine.
