### ISSUE TITLE
Feature Request: OAuth2 login

### ISSUE THREAD

**Issue by yutachaos** [parseablehq/parseable#410]
# Description
I kindly request the implementation of OAuth2 login in Parseable. OAuth2 is a widely adopted authentication protocol known for its secure and user-friendly login mechanism. Integrating OAuth2 login into Parseable would greatly enhance the functionality and convenience for users.

With OAuth2 login, Parseable users would be able to sign in using their existing accounts from popular platforms like Google, Facebook, or GitHub. This eliminates the need for users to create new credentials specifically for Parseable, simplifying the authentication process and reducing friction.

**Comment by nitisht** [comment]
Thanks @yutachaos , I agree this will be indeed useful. we'll add this to the roadmap.

**Comment by scholz-timo** [comment]
Would love this for more convenient deployment.

**Comment by nitisht** [comment]
We're going to prioritise this @scholz-timo . Thank you for the comment.
