### ISSUE TITLE
bug: after deleting a log stream, still able to get the stats for that logstream

### ISSUE THREAD

**Issue by nitisht** [parseablehq/parseable#412]
Steps 

1. Create a log stream.
2. Ingest events to the log stream.
3. Get stats of the log stream.
4. Delete the log stream.
5. Call list stream API to see the stream is actually deleted.
6. Get stats of the log stream --> expectation is that API fails with 404, but currently it returns the last recorded stats of the stream.

**Comment by davidrhp** [comment]
I have had a look at the docs and code and would like to work on this.

**Comment by nitisht** [comment]
Thanks @davidrhp . Moving this to you.
