### ISSUE TITLE
Docker container crashes everytime!

### ISSUE THREAD

**Issue by elliot40404** [parseablehq/parseable#423]
![image](https://github.com/parseablehq/parseable/assets/67360013/a49ea739-6a13-4b43-a777-0606b9dc6bca)

Tried with different s3 buckets, minio, localstack nothing works. Only works in local storage mode.

**Comment by nitisht** [comment]
@elliot40404 can you try with an empty bucket? Looks like the bucket is not empty

**Comment by elliot40404** [comment]
Thank you very much that worked!
