### ISSUE TITLE
Different results with the same filter 

### ISSUE THREAD

**Issue by makorne** [parseablehq/parseable#424]
Hi!
Thank you for great crate.

But sometimes I see strange issues with search in logs.
For example - search with same filter (just number like 12345678, exists in logs) for today ( may 25 ) data.
 24 h/ 3days / 7Days - absolutly different results

 24h:
![24HScreenshot_2023-05-25_16-00-40](https://github.com/parseablehq/parseable/assets/26540498/bf666cb6-af98-437d-ba1d-fa8081887851)

Again 24h:

![24H2Screenshot_2023-05-25_16-00-40](https://github.com/parseablehq/parseable/assets/26540498/5e7f2c7b-fe92-482b-9169-ce2a614a8bca)

3 days:

![3DaysScreenshot_2023-05-25_15-59-55](https://github.com/parseablehq/parseable/assets/26540498/f2e8f9c8-50df-4e4d-a3de-79cfcbfa4ce4)

7 days:

![7DaysScreenshot_2023-05-25_16-03-08](https://github.com/parseablehq/parseable/assets/26540498/a2584af7-56cf-4b93-86b5-8f8985d660ed)

**Comment by nitisht** [comment]
Thank you for reporting this @makorne . This looks a console issue - are you able to try Query API directly https://www.parseable.io/docs/api/log-query and verify if this happens in the query response as well? 

This will help us define the problem area and fix it faster.

**Comment by nitisht** [comment]
@makorne we were not able to reproduce this ourselves. Closing this due to lack of response. Feel free to reopen if this is still happening
