### ISSUE TITLE
Datafusion Optimizations and Integrations

### ISSUE THREAD

**Issue by trueleo** [parseablehq/parseable#447]
Tracking issue for things to be done in order to fully integrate Datafusion with Parseable and solve some of the existing query issues.
 

- [x] Better partition pruning and query performance on  `order by p_timestamp DESC`.
- [x] Add physical optimizer to remove SortMergeExec on `order by` queries.
- [x] ~~Add physical optimizer to preserve partition order on `select * from table` as they are already sorted in ascending order.~~ Sort order is now Desc and single partition preserves order for simple select query 
- [x] Add optimization based on the fact that data is non overlapping on timestamp column
- [x] Integrate `datafusion::catalog`.

**Comment by trueleo** [comment]
There is a discussion about SortMergeExec issue here https://github.com/apache/arrow-datafusion/issues/6672

**Comment by nitisht** [comment]
Fixed in recent commits. Closing this.
