### ISSUE TITLE
Request to Add Support for ARM Architecture

### ISSUE THREAD

**Issue by masudhan** [parseablehq/parseable#449]
Hi Team,

I kindly request parseable to consider adding support for the ARM architecture in the platform. This would greatly benefit organisations that have migrated or plan to migrate to ARM-based infrastructure. ARM architecture is gaining popularity due to its energy efficiency, scalability, and widespread adoption in modern computing environments.

Also, request you to add docker image to [AWS Public Gallery](https://gallery.ecr.aws/) and others as well

Thanks,
Madhu

**Comment by nitisht** [comment]
Thanks @deamonkillerM we'll get to this soon.

**Comment by nitisht** [comment]
@deamonkillerM we added ARM build for the new release https://github.com/parseablehq/parseable/releases/tag/v0.6.0

Will add docker image soon.

**Comment by helmut72** [comment]
I found this issue because I wanted to start it on my Raspberry ;)

**Comment by patrickdung** [comment]
Is the Arm64 for MAC or Linux?

If it is Linux arm64
I have some work done in my repo https://github.com/patrickdung/parseable/blob/main/.github/workflows/github-release.yml
Currently it just save the binary as artifact only.

**Comment by aldrinjenson** [comment]
Hey @patrickdung, just wanted to tell you thanks for sending your version of the workflow. 
I used it as a first inspiration to create a new GitHub action workflow that builds Parseable for all common architecture including linux arm 64bit.
Right now the new workflow is tested with pull requests. It's supposed to creates binary artifacts and add them automatically in releases. Let's see it action for the next Parseable release which is coming soon.🤞
