### ISSUE TITLE
Will parseable support storing prometheus metrics and traces?

### ISSUE THREAD

**Issue by batmilkyway** [parseablehq/parseable#491]
As an SRE/platform/cloud/whatever engineer I'd like to self-host my observability tools to reduce costs (DataDog, New Relic, etc are quite costly). One of the pain points with self-hosting is that tools are either fragmented, or require heavy infrastructure investment.

For example, the LGTM stack requires deploying Loki, Tempo, and Mimir (or other Prometheus compatible store) to capture logs, metrics, and traces.

Other projects like SigNoz or Uptrace, which do support a unified observability store, do it with ClickHouse, which can be pretty resource hungry and also incurs operational overhead.

Are there any plans to eventually support storing metrics and traces?

**Comment by nitisht** [comment]
Thanks for the questions @batmilkyway , let us get back on this in sometime. We've been discussing internally about this for a while and we'll have a plan shortly.

**Comment by nitisht** [comment]
@batmilkyway we discussed about this internally and as of now we'll focus on logs and related use cases.
