### ISSUE TITLE
New IngestOnly role?

### ISSUE THREAD

**Issue by kepi** [parseablehq/parseable#501]
Hi,

is there any plan to support **ingest only** role? At this moment, I would like to create user for untrusted app, which would push logs to my parseable instance. With **Writer** role, user can also query logs on *stream*, which doesn't seem necessary for *"agent"*.

My original thought was to temporarily use *Parseable* directly from front-end (browser) app, but even if this isn't the dcase, I see same problem with using *Parseable* i.e. for server logs. I would have to separate steams for every server, or do some other magic to prevent cross server logs visibility. IMHO role with only `Ingest` action would be simpler solution?

Thanks for considering and/or any thoughts on this.

**Comment by nitisht** [comment]
hey @kepi this is a good point. Eventually we'd like the user to be able to create fine grained roles (specify which APIs can be called). But right now a ingest only role would be useful, agreed. We'll prioritise this.

**Comment by nitisht** [comment]
Fixes in #504, will be available in the next release @kepi

**Comment by kepi** [comment]
Huge thanks for getting to this so quickly!
