### ISSUE TITLE
New log streams not showing up in log streams list

### ISSUE THREAD

**Issue by 123vivekr** [parseablehq/parseable#51]
I was able to create a log stream but it wont show up when I list the streams, even when I have successfully pushed logs into the stream.

# How to reproduce?
1. Delete log stream (in-case it exists already)
```
curl --request DELETE "http://0.0.0.0:8000/api/v1/logstream/testnewlogbug" --header 'Authorization: Basic cGFyc2VhYmxlOnBhcnNlYWJsZQ=='
```
2. Create a new log stream `testnewlogbug`
```
curl --request PUT "http://0.0.0.0:8000/api/v1/logstream/testnewlogbug" --header 'Authorization: Basic cGFyc2VhYmxlOnBhcnNlYWJsZQ=='
```
3. List log stream
```
curl --request GET "http://0.0.0.0:8000/api/v1/logstream" --header 'Authorization: Basic cGFyc2VhYmxlOnBhcnNlYWJsZQ=='
```

The stream `testnewlogbug` does not show up.
Double check if `testnewlogbug` folder is present in s3
```
aws --endpoint=https://sgp1.digitaloceanspaces.com --region="sgp1" s3 ls s3://parseable/
```

**Comment by 123vivekr** [comment]
@nitisht Can you assign this to me?

**Comment by nitisht** [comment]
yes..done

**Comment by 123vivekr** [comment]
Update: Seems like only stream names starting with `test` aren't getting listed.

![image](https://user-images.githubusercontent.com/28249428/186613246-e5bf08e3-7055-4df3-96d8-b54f99ca3f63.png)

NOTE: I'm testing on the "live demo" given in the README.md

**Comment by 123vivekr** [comment]
The problem is with either the AWS SDK or DO Spaces API

**Comment by nitisht** [comment]
we're moving to MinIO as the default demo storage with #65 we can test after that PR is merged
