### ISSUE TITLE
Improve errors related to object storage authentication.

### ISSUE THREAD

**Issue by trueleo** [parseablehq/parseable#52]
New error variant on `ObjectStorageError` is needed to correctly display authentication failure and let users know if credentials provided are wrong.

Currently on authentication failure, `ObjectStorage::check` returns `Unhandled Error: Error`. This method for S3 is implemented by call to `head_bucket` which returns `aws_sdk_s3::types::SdkError<HeadBucketError>` but is mapped to unhandled error variant.

**Comment by 123vivekr** [comment]
Can I work on this?
Please assign this to me

**Comment by nitisht** [comment]
Sure @123vivekr please go ahead
