### ISSUE TITLE
Parseable incorrectly extracts stream name from query when using arrow datafusion extract

### ISSUE THREAD

**Issue by stanvanrooy** [parseablehq/parseable#535]
It is currently not possible to use the `extract` function because the syntax of it confuses Parseable. Can be easily reproduced by running the query below in the demo environment.

```sql
SELECT extract(epoch FROM p_timestamp) FROM backend
```

I'd be more than happy to contribute on a fix, if someone can point me in the right direction.

**Comment by trueleo** [comment]
@stanvanrooy I'll look into fixing this for upcoming release. The parsing for stream name is what is causing this issue. 

You may rewrite your query as follow so that the table name comes first. This is stream name is used for query planning.

```sql
WITH tab AS (
  SELECT * FROM backend
)
SELECT extract(epoch FROM p_timestamp)
FROM tab;
```
