### ISSUE TITLE
Feature: Upload logs to S3 by specific folder path

### ISSUE THREAD

**Issue by AhmedmmAli** [parseablehq/parseable#554]
Data is uploaded to S3 by this file structure Day/hour/MIN
We want to upload the data to the S3 by this file structure Month/Day/Hour/Min
![MicrosoftTeams-image (4)](https://github.com/parseablehq/parseable/assets/10684247/270ae016-4b37-4aa9-b0bd-3275a902bdfd)
![MicrosoftTeams-image (5)](https://github.com/parseablehq/parseable/assets/10684247/76a479fc-567b-48fc-81b1-286edc6ae6c6)

**Comment by nitisht** [comment]
Closing this due to lack of response. Feel free to reopen if you have further comments
