### ISSUE TITLE
[Bug] Create stream does not work with s3 object lock enabled.

### ISSUE THREAD

**Issue by AhmedmmAli** [parseablehq/parseable#555]
This feature was enabled in older parseable versions but now it's not working any more.
This PR is not merged to the latest parseable version: https://github.com/parseablehq/parseable/pull/218

**Comment by nitisht** [comment]
hi @AhmedmmAli have you set ‘ P_S3_SET_CONTENT_MD5’ to true in your Parseable setup environment?

**Comment by AhmedmmAli** [comment]
@nitisht Yes I did, and it was working before, and when We tried to upgrade the parseable version, It stopped working

**Comment by nitisht** [comment]
Thanks we'll take a look

**Comment by trueleo** [comment]
This feature was removed due to changes in object-store layer. You can still do object integrity check by setting env flag `P_S3_CHECKSUM` to true.

**Comment by AhmedmmAli** [comment]
@trueleo Thanks I tested it and it works fine

**Comment by nitisht** [comment]
thanks for the confirmation @AhmedmmAli closing this issue
