### ISSUE TITLE
Set Alert: target "repeat" property set to default when omitted 

### ISSUE THREAD

**Issue by jybleau** [parseablehq/parseable#556]
Hi,

When setting an alert (I use the API), the optional `repeat` does not seem to be optional:

### Put data, no `repeat`
```
{
  "version": "v1",
  "alerts": [
    {
      "targets": [
        {
          "type": "slack",
          "endpoint": "https://hooks.slack.com/services/NOP/NOPNOP/NOPNOPNOP"
        }
      ],
      "name": "Alert: Server side error",
      "message": "Warning: {label} {message}",
      "rule": {
        "type": "column",
        "config": {
          "column": "level",
          "operator": "=",
          "value": "warning",
          "repeats": 1
        }
      }
    }
  ]
}
```

### Get data, the default `repeat` appears

```
{
    "version": "v1",
    "alerts": [
        {
            "targets": [
                {
                    "type": "slack",
                    "endpoint": "https://hooks.slack.com/services/NOP/NOPNOP/NOPNOPNOP"
                    "repeat": {
                        "interval": "3m 20s",
                        "times": 5
                    }
                }
            ],
            "name": "Alert: Server side error",
            "message": "Warning: {label} {message}",
            "rule": {
                "type": "column",
                "config": {
                    "column": "level",
                    "operator": "exact",
                    "ignoreCase": null,
                    "value": "warning",
                    "repeats": 1
                }
            }
        }
    ]
}
```

### Version info

- Commit: 41029fd
- Version: v0.7.1
- UI Version: v0.3.4

**Comment by nitisht** [comment]
Thanks for reporting, @jybleau . Is the issue here that repeats field, even if not set by you, is set as 1?

**Comment by trueleo** [comment]
@jybleau Target's repeat field dictates how many times to re send the alert once it has been triggered. This has a default configuration that can only be overridden. If you want to receive alerts only minimal number of times then `repeat.times` should be set to `0` .

This will send alert only when trigger condition is met and one resolve message when condition resolves

**Comment by jybleau** [comment]
@trueleo Thanks for the clarification. Since `repeat` is an optional field, I implied omitting it meant deactivating repetition.
Maybe it should be added to the documentation that there is a default value for `repeat` and what this default value is.

**Comment by trueleo** [comment]
Thanks, We will add document this behavior more thoroughly. I will be closing the this issue now.

**Comment by nitisht** [comment]
@trueleo reopening this so we can track the docs update.
