### ISSUE TITLE
Message format feature not replacing placeholders with correct value

### ISSUE THREAD

**Issue by jybleau** [parseablehq/parseable#564]
Was trying to use the message format feature described in: 
https://www.parseable.io/docs/alerts#message and [#331](https://github.com/parseablehq/parseable/issues/331)

i can create an alert with this message property value: `"message": "Error: {label} {message}",`

But when I trigger an alert, the message sent to the Slack target webhook is still: 
"message": "Error: {label} {message}",

The placeholders and not replaced by the corresponding values.

Also, the documentation states: 

> The {**status_code**} is a placeholder that will be replaced with the value of the **_status_** column in the event that triggered the alert.

For the sake of clarity, should we read instead: [...] value of the **_status_code_** column [...] ?

Thanks!

_ref: Slack conversation with @nitisht_ 

**Installed version**

Commit:41029fd
Version:v0.7.1
UI Version:v0.3.4

**Comment by nitisht** [comment]
Thanks for reporting @jybleau we'll fix this.

**Comment by nitisht** [comment]
Have you tried with a single value in the `message` field? e.g. `"message": "Error: {error_column}",` (here `error_column` is the column that you want to print.

**Comment by jybleau** [comment]
Ok! it works with a single param: `"message": "Error: {message}"`

Would you add support for multiple values? Or update the documentation.

Thanks

**Comment by nitisht** [comment]
We'll get back on multi columns support @jybleau
