### ISSUE TITLE
Parseable server start error with s3-store

### ISSUE THREAD

**Issue by nikhilsinhacloudsurfex** [parseablehq/parseable#573]
Error occurs in starting Parseable server with s3-store.

Steps to reproduce-

Start Minio in Local -
1. Download minio executable
2. Run below command -
    MINIO_ROOT_USER=admin MINIO_ROOT_PASSWORD=password ./minio server /tmp/data --console-address ":9001"
3. Open browser and type localhost:9000 and login with user=admin, password=password
4. Create bucket with name - "parseable-main"

Start Parseable server in Local -

1. Clone parseable code from main branch
2. cargo build
3. set below environment variable -
4. export P_ADDR=0.0.0.0:8000
export P_S3_URL="http://localhost:9000/"
export P_S3_ACCESS_KEY="admin"
export P_S3_SECRET_KEY="password"
export P_S3_REGION="us-east-1"
export P_S3_BUCKET="parseable-main”
export P_USERNAME="admin"
export P_PASSWORD="admin"
5. Run below command - 
./target/debug/parseable s3-store

Below error occurs -

Error: Unhandled Error: Could not start the server because metadata not found in storage. Join us on Parseable Slack to report this incident : https://launchpass.com/parseable

Then Open parseable folder and delete Staging folder and run the command again, it works.

Please look into the issue.

**Comment by alexmdcampo** [comment]
same here
