### ISSUE TITLE
generate sql query is not working

### ISSUE THREAD

**Issue by AswinKumarVenketesan** [parseablehq/parseable#581]
I have added openai.api.key in parseable-env-secret and created it in Kubernetes with kubectl create secret command but I can't see the generate log box in UI 
![Screenshot 2023-12-19 at 10 57 08 PM](https://github.com/parseablehq/parseable/assets/51033679/53d40dce-5075-4346-97e9-7673e2dd3f1b)

**Comment by nitisht** [comment]
We'll take a look shortly @AswinKumarVenketesan . Thanks for reporting.

**Comment by nitisht** [comment]
Fixed, correct link for docs is: https://www.parseable.io/docs/integrations/llm
