### ISSUE TITLE
Encountering a cross-origin issue in Chrome. How can I address this problem?

### ISSUE THREAD

**Issue by fxjs** [parseablehq/parseable#589]
This is a great project, but starting from v0.7.1, calling the API using Chrome results in a CORS error. I attempted to configure an NGINX reverse proxy, but it didn't resolve the issue. Is there something that needs to be configured in the settings file?
v0.7.0 worked fine.

```text
Commit:
41029fd
Version:
v0.7.1
UI Version:
v0.3.4
Deployment Id:
01HAVTY6RG0CKHHJ3GFJ6AJMMT
Mode
Local drive
Staging
/var/lib/parseable/staging
Store
/var/lib/parseable/data
LLM Status
LLM API Key not set
```
Screenshot:
![image](https://github.com/parseablehq/parseable/assets/3682415/c4a36917-299b-4ad2-a7c5-d9603f819e94)

**Comment by nitisht** [comment]
How are you running Parseable here @fxjs - are you running the frontend / console separately?

**Comment by fxjs** [comment]
> How are you running Parseable here @fxjs - are you running the frontend / console separately?

Runs in a separate test webpage with the Chrome console open.

Screenshot:

![2023-12-28-090248_1920x1080_scrot](https://github.com/parseablehq/parseable/assets/3682415/de044480-3bf4-4f6e-90ec-683d8b6c933b)


SourceCode:

[cors-demo.zip](https://github.com/parseablehq/parseable/files/13782318/cors-demo.zip)

**Comment by nitisht** [comment]
hey @fxjs sorry for the delayed response. I tried this and can repro the issue. But the problem here is that it is not intended to run Console as a separate server and access parseable server remotely. 

Console is built-in the Parseable binary and it is recommended to run that console by accessing the Parseable server IP / DNS name. 

I'd like to understand what is the use case here to run Parseable separately.

**Comment by nitisht** [comment]
Closing this for now, please feel free to reopen if there is confusion.

**Comment by fxjs** [comment]
> hey @fxjs sorry for the delayed response. I tried this and can repro the issue. But the problem here is that it is not intended to run Console as a separate server and access parseable server remotely.
> 
> Console is built-in the Parseable binary and it is recommended to run that console by accessing the Parseable server IP / DNS name.
> 
> I'd like to understand what is the use case here to run Parseable Console separately.


The scenario I'm working on involves the need to log web page operations. I resolved the issue by configuring Nginx to allow cross-origin requests. The problem was that I hadn't included cross-origin configuration within the options, which caused the API interface calls to fail. The correct configuration is as follows:
```nginx.conf
add_header Access-Control-Allow-Origin * always;
add_header Access-Control-Allow-Headers *;
add_header Access-Control-Allow-Methods "GET, POST, PUT, OPTIONS";

if ($request_method = 'OPTIONS') {
    add_header Access-Control-Allow-Origin * always;
    add_header Access-Control-Allow-Headers *;
    add_header Access-Control-Allow-Methods "GET, POST, PUT, OPTIONS";
    
    return 206;
}

```

Tks.
