### ISSUE TITLE
Docs in Need help section of About Parseable page doesn't link to correct docs page.

### ISSUE THREAD

**Issue by atamakahere-git** [parseablehq/parseable#591]
Currently it links to : https://www.parseable.com/docs/introduction (Page not found)
It should be: https://www.parseable.com/docs/

![Screenshot_20240102_180819](https://github.com/parseablehq/parseable/assets/13798805/77e2d756-52c4-4087-acd4-7c89af9edf5d)

Using the latest commit on master branch a3f9ccb89f6b40cea8e68a1635f058d92aff1055

**Comment by nitisht** [comment]
Thanks, we'll fix this shortly

**Comment by nitisht** [comment]
Fixed by https://github.com/parseablehq/console/pull/168

**Comment by atamakahere-git** [comment]
Reopening because "[Enable SQL generation with OpenAI](https://www.parseable.io/docs/api/llm-queries)" is also broken on the dashboard

![image](https://github.com/parseablehq/parseable/assets/13798805/99ff0cb6-2e80-4fe7-a1d3-64dd31f8d50e)
