### ISSUE TITLE
bug: TLS for gRPC / live tail connection

### ISSUE THREAD

**Issue by nitisht** [parseablehq/parseable#608]
Live tail support doesn't work if Parseable server is running with TLS configured. This is because the `gRPC` server (Tonic) has the TLS configuration missing. 

Refer original live tail issue: https://github.com/parseablehq/parseable/issues/503
Refer: https://github.com/parseablehq/parseable/blob/main/server/src/handlers/livetail.rs#L165-L186

**Comment by Eshanatnight** [comment]
I found some examples, that implement certificates and identities from tonic and with rustls. What I am seeing is both the implementations will need a newer version of rustls, **above** `0.21.10`. Current version is at `0.20`

**Comment by nitisht** [comment]
That should be okay, we can upgrade `rustls`
