### ISSUE TITLE
request: AWS EKS - Service Account over IAM user

### ISSUE THREAD

**Issue by parisnakitakejser** [parseablehq/parseable#611]
What i think needed are a way to not use secret and key to connection to my S3 folder, the most secure way are add the service account and allow that into AWS EKS as a service account there are connected to a role inside AWS.

Hope that feature can be integrated :)

**Comment by nitisht** [comment]
Do you mean something like this https://github.com/parseablehq/parseable/issues/393

**Comment by parisnakitakejser** [comment]
Yes, but if i remove the secret/key from my helm its wont start Parsable up, so my there are a bug with that so? :) I just think its becures its not supported it right now but yeah its what I mean with service account :)

**Comment by nitisht** [comment]
ah this might be a helm chart issue. we'll check

**Comment by nitisht** [comment]
Thanks for the info @gyoza . @parisnakitakejser closing this for now as we have clarity on how to add this. Feel free to reopen if there are further issues.
