### ISSUE TITLE
Sending logs to Kafka data stream

### ISSUE THREAD

**Issue by parisnakitakejser** [parseablehq/parseable#618]
The idé of this request will be its sending to S3 paquest format, its fine, but if you have a Data Lakehouse its mabey makesens to allow to sending the logs to a Kafa data stream so a data-team can get easy access to it and manipulate the data ingress option if needed, just a ide if its sounds to crazy just ignore my ide :)

**Comment by nitisht** [comment]
Hey @parisnakitakejser idea definitely makes sense. But any log agent like Vector / FluentBit etc can directly send logs to several targets including Kafka. So I think for this use case that you mentioned, it is better to configure the log agent to directly send events to Kafka. 

For example, refer the docs below:
- https://vector.dev/docs/reference/configuration/sinks/kafka/
- https://docs.fluentbit.io/manual/pipeline/outputs/kafka

**Comment by nitisht** [comment]
I hope this answer is useful @parisnakitakejser - closing the issue for now. Happy to discuss further, here or on Slack if there are queries.
