### ISSUE TITLE
Cost reduction request: Use Delta Lake with Parquet for better Comparison/Objects numbers

### ISSUE THREAD

**Issue by parisnakitakejser** [parseablehq/parseable#628]
A way to do a better comparison/objects and lower data cost in S3 will be to add Delta Lake as format with parquet, its will reduce the files over time, and allow to keep history for the files if needed.

its possible to read more about [Delta Lake](https://delta.io/blog/delta-lake-vs-parquet-comparison/)

hopes this quest can help to even faster performs for queries and save in general the cost when searching

So the idé using Data Lake will collect all the normal parquet files into smaller numbers, and because it uses AWS S3, it will reduce the number of object requests to AWS and over all reduce the cost for the software user.

**Comment by gladkikhartem** [comment]
FinOps expert here.

How it will reduce the cost?
Parquet is pretty efficient by itself, especially if data is sorted properly. 
The difference is only if I need to download metadata from 10 or 100 files, which is really not a problem, because you can cache it locally (good example is DuckDB).

**Comment by parisnakitakejser** [comment]
Delta Lake is not a new format, it's a way to use parquet files stack them together, remove unused formats, and automatically expire files if needed. 

Eg. if you have 1000 small files, and then stack them into a single one, it will reduce the cost because it only 1 object and not 1000 objects you search data from, I know it does not scan all your files every time but if I want to see data from eg. last 30 days, it needs to give. me the data based on metadata and here it's more cost-effective to serve 1 file a day and not 1000 files per day, and the size of the total file will be smaller too.

There can be other ways around this cost issue, but it's excellent stuff to reduce the AWS S3 Object requests in general.

I have multiple certifications in AWS and Kubernetes, so I just try to share import to do the software even better to lower the cost eg. S3.

**Comment by nitisht** [comment]
@parisnakitakejser thank you for the idea here. We discussed this internally - the issue we're trying to fix here really is reduce the number of files, right? We can address that with a compaction engine that works in tandem with Parseable ingestion and retention. This is on our roadmap. We'll get to this in some time.

I think adding Delta Lake will be an overkill here - Delta Lake is designed for database like properties (delete rows, update rows) which are irrelevant for a log analytics system where events are immutable (there are no updates / upserts etc). So closing this issue. Feel free to reopen / comment if you think other wise.

**Comment by parisnakitakejser** [comment]
Thanks for the feedback, yeah the main issue is to many small files in general, so what you use to reduce and vacuum the files into smaller parts is something you know better then me, Delta Lake was just to point out my goal of the problem ^^ but it's sound as you get my points and looks great when that feature are added :)
