### ISSUE TITLE
OIDC not working with Keycloak

### ISSUE THREAD

**Issue by truediogo** [parseablehq/parseable#638]
I'm getting error 401 after login in a parseable instance with OIDC setup as in docs (https://www.parseable.com/docs/oidc).

Url on redirect after login

> https://urlhere.com/api/v1/o/code?state=https%3A%2F%2Furlhere.com%2F&code=9f78babe-5125-49d4-a548-bf32c7062311.de84c384-b522-40d4-82b2-d3f0681490e8.dcdf820d-494a-44a3-a3a4-f47e90628d97

Error in Keycloak

> 2024-01-29 11:31:55,135 WARN  [org.keycloak.events] (executor-thread-2336) type=CODE_TO_TOKEN_ERROR, realmId=2ddb18f7-9c9d-4e28-84b0-b90e8d2a676f, clientId=parseable, userId=null, ipAddress=10.0.0.1, error=invalid_code, grant_type=authorization_code, code_id=de84c384-b522-40d4-82b2-d3f0681490e8, client_auth_method=client-secret

Missing something?

**Comment by nitisht** [comment]
Thanks for reporting @truediogo we'll take a look

**Comment by nitisht** [comment]
@nikhilsinhacloudsurfex will get back shortly on this one @truediogo .
