### ISSUE TITLE
Typo : Wrong URL for helm repo

### ISSUE THREAD

**Issue by olevitt** [parseablehq/parseable#646]
Hello,

I could not find the source repo for the documentation but there is a typo in https://www.parseable.com/docs/installation/kubernetes-helm#install-parseable-1 , charts repo URL should be `https://charts.parseable.io` instead of `https://charts.parseable.com`

**Comment by nitisht** [comment]
thanks for reporting @olevitt we'll fix it right away

**Comment by olevitt** [comment]
@nitisht It looks like you just switched from `https://charts.parseable.io` to `https://charts.parseable.com`. Sadly the `index.yaml` now hosted at `https://charts.parseable.com` still references `https://charts.parseable.io`  as URL for packages. As `charts.parseable.io` no longer have DNS associated this makes the chart repo unusable.  
Steps to reproduce :   
```
helm repo add parseable https://charts.parseable.io
```  
This works as it's loading the `index.yaml` fine.  
But then 
```
gon@laboitemagique:~$ helm template parseable/parseable 
Error: Get "https://charts.parseable.io/helm-releases/parseable-0.7.3.tgz": dial tcp: lookup charts.parseable.io: no such host
```

Charts are still gettable manually on `https://charts.parseable.com/helm-releases/parseable-0.7.3.tgz` but that's not the URL that are referenced in the `index.yaml`.
I think the `index.yaml` should be updated

**Comment by nitisht** [comment]
Thanks for the pointers, @olevitt . Fixed now: https://charts.parseable.com/index.yaml

I had to manually update `helm-index.sh` file.
