### ISSUE TITLE
Use tokio async runtime instead of std::thread

### ISSUE THREAD

**Issue by Eshanatnight** [parseablehq/parseable#652]
Update the architecture to use tokio tasks instead of threads

[Tokio Docs](https://docs.rs/tokio/latest/tokio/task/index.html)

Edit: add documentation link

**Comment by nitisht** [comment]
Can you link to tokio tasks doc pls

**Comment by sinhaashish** [comment]
Please assign this to me.

**Comment by vishalkrishnads** [comment]
may i try this?

**Comment by nitisht** [comment]
Sure @vishalkrishnads
