### ISSUE TITLE
upgrade failed from  0.7.3 to 0.8.0

### ISSUE THREAD

**Issue by spijker** [parseablehq/parseable#667]
Trying to update parseable from 0.7.3 to 0.8.0 using helm failed.

The error : 
```
        Commit:             "22c82c4"
2024-02-19T07:18:35.204661882Z         Docs:               "https://logg.ing/docs"
2024-02-19T07:18:35.204832602Z 
2024-02-19T07:18:35.415105159Z thread 'main' panicked at server/src/storage/object_storage.rs:199:53:
2024-02-19T07:18:35.415145247Z parseable config is valid json: Error("missing field `retention`", line: 1, column: 6186)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by nitisht** [comment]
This is a regression, we heard from others as well - we'll make a new release shortly with a fix. My sincere apologies for this and thank you for reporting.

**Comment by nitisht** [comment]
For now you can continue using `v0.7.3`

**Comment by nitisht** [comment]
cc @gurjotkaur20 I have reverted #661 for now. We need to add it in a backward compatible manner.

**Comment by gurjotkaur20** [comment]
Yes, will do changes accordingly.

**Comment by nitisht** [comment]
Updated release is available - binaries and docker images will be available shortly https://github.com/parseablehq/parseable/releases/tag/v0.8.1

**Comment by nitisht** [comment]
everything is available now. closing this. please use `v0.8.1`
