### ISSUE TITLE
Incorrect code fragment in documentation in (at least) "Application Integration" -> "Python"

### ISSUE THREAD

**Issue by thinkORo** [parseablehq/parseable#670]
I tried to select some data via Parseable API using Python. For this I followed the documentation in: https://www.parseable.com/docs/log-ingestion/applications/python

The code snippet (at least) for "Querying a log stream" is wrong as the provided format for startTime and endTime is wrong.

Current documentation:
```
"startTime": "2022-09-10T08:20:00 00:00",
"endTime": "2022-09-10T08:20:31 00:00"
```

But should be:
```
"startTime": "2022-09-10T08:20:00+00:00",
"endTime": "2022-09-10T08:20:31+00:00"
```

**Comment by nitisht** [comment]
Thanks for reporting @thinkORo . Fixed it now: https://www.parseable.com/docs/log-ingestion/applications/python

Closing this issue as resolved.
