### ISSUE TITLE
feat: allow arrow response for query

### ISSUE THREAD

**Issue by nitisht** [parseablehq/parseable#672]
We should allow for an arrow response in a streaming fashion when a query is run. This will make time to first byte much faster and also allow integration with existing arrow ecosystem tools.

Console can leverage the arrow response. 

We can still keep the json response for query as the default response but add a flag in query body, looking at the flag server can respond in arrow format.

**Comment by nitisht** [comment]
Implementation at #769

**Comment by thinkORo** [comment]
Hi @nitisht is there any plan for a specific version with this feature? I would be very interested in testing it.

For your information: I am currently working on a kind of open-source (meta) data catalog. And I use Parseable together with Vector for my logs.

I'm not sure if I will ever publish it, but as there is no other place, currently: I want to say thank you for your work on this project. Very inspiring.

**Comment by nitisht** [comment]
fixed by #769

**Comment by nitisht** [comment]
> Hi @nitisht is there any plan for a specific version with this feature? I would be very interested in testing it.
> 
> For your information: I am currently working on a kind of open-source (meta) data catalog. And I use Parseable together with Vector for my logs.
> 
> I'm not sure if I will ever publish it, but as there is no other place, currently: I want to say thank you for your work on this project. Very inspiring.

Thanks for the interest @thinkORo this will be available in the next release 1.1.1 on the server. We still might need more time to utilise this in the console.

Happy to discuss further as needed.
