### ISSUE TITLE
OAUTH Authenticated users not shown correctly

### ISSUE THREAD

**Issue by imagdy83** [parseablehq/parseable#686]
when a user logs in via oauth, the username is displayed as jiberish as shown in the image attached 
Username should be mapped correctly
![image](https://github.com/parseablehq/parseable/assets/36445754/eefe28b0-bfd7-4485-b69b-97a9c53b1850)

**Comment by imagdy83** [comment]
any updates?

**Comment by nitisht** [comment]
Fixed by #742

**Comment by imagdy83** [comment]
@nitisht issue has not been resolved, and it is unrelated to keycloak

**Comment by imagdy83** [comment]
> when a user logs in via oauth, the username is displayed as jiberish as shown in the image attached Username should be mapped correctly ![image](https://private-user-images.githubusercontent.com/36445754/310102417-eefe28b0-bfd7-4485-b69b-97a9c53b1850.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NTcwMjUsIm5iZiI6MTcxMjY1NjcyNSwicGF0aCI6Ii8zNjQ0NTc1NC8zMTAxMDI0MTctZWVmZTI4YjAtYmZkNy00NDg1LWI2OWItOTdhOWM1M2IxODUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA5NTg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlY2YzNGM1NjY3MmFhMGEwNTVmZDY1Mzk2ODRlYWFlNDhiYjlmYmRmNDYwN2FjYjI4YWYyNGQwMDkwZGQzOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZBS8mxObcWF0k-2TS9dtqFYAx1jWhYxFCjAsnPv6fF4)

@nitisht  users are still displayed as gibberish

**Comment by nitisht** [comment]
What is the version you're running? We've not yet made the release.

**Comment by imagdy83** [comment]
If the release wasn't made why was this issue closed and marked as solved by the latest release? 🤨
I'm running on the latest release 0.9.0

**Comment by nitisht** [comment]
> Fixed by https://github.com/parseablehq/parseable/pull/742

This is the comment. It doesn't say latest release, it is implied that it will be available when new release is made. What are you expecting?

**Comment by nitisht** [comment]
> I expect the issue to be closed with the problem fixed which is not the case.

Issue is closed because it is fixed in main. It will be available when we make the next release. Hope this clarifies. Thank you for the patience.
