### ISSUE TITLE
add azure blobstore support as object store backend

### ISSUE THREAD

**Issue by nitisht** [parseablehq/parseable#687]

**Comment by dharanad** [comment]
hello @nitisht as discussed can you please assign this to me.

**Comment by nitisht** [comment]
Sure @dharanad done.

**Comment by brainless** [comment]
Hey @nitisht just came across this from Algora. Will take a look around the product first and let you know if I can pick this up. I am building my own product in graph + llm space with search on top so Parseable looks cool.

**Comment by piyushsingariya** [comment]
Hi @nitisht I am giving a try to this issue.
