### ISSUE TITLE
Helm : version 0.9 and 0.9.0 confuses helm dependencies resolution

### ISSUE THREAD

**Issue by olevitt** [parseablehq/parseable#690]
Hi !   

I saw you released 2 versions of the helm chart : `0.9` and `0.9.0`.  
`0.9` seems to be buggy (tries to pull un-existing `0.9` image tag).  
Installation seems fine using `0.9.0`.
Thing is, when using parseable as a helm dependency (typical use case is creating a wrapper helm chart) helm is confused and resolves `0.9` as a matching version for `0.9.0` (probably a semver check that goes wrong).  
Just wanted to let you (and other users) know this.  
I don't have any workaround so I will stick with 0.8.1 waiting for a new release.

**Comment by nitisht** [comment]
Thanks @olevitt - let me see if I can completely un-publish the version `v0.9`
