### ISSUE TITLE
bug: Incorrect Data Returned When Querying at 1-Minute Intervals

### ISSUE THREAD

**Issue by MinCrohn** [parseablehq/parseable#692]
I conducted queries at 1-minute intervals across various time zones and discovered that incorrect data is occasionally returned. This issue was also found in the 'backend' stream of your provided Demo site.
([https://demo.parseable.com/backend/logs](https://demo.parseable.com/backend/logs))

The first query was requested at a 1-minute interval, and no results were returned.

In the second query, I extended the request to a 2-minute interval and confirmed that the data corresponding to the first query does exist. Note that in the second query, the data didn't start from 22:00:00, but from 22:01:00 instead. Please take this into consideration.

1. body:

```
{
    "query": "select p_timestamp from backend",
    "startTime": "2024-03-06T22:01:00+00:00",
    "endTime": "2024-03-06T22:02:00+00:00"
}
```

1. result:

```
[]
```

1. body:

```
{
    "query": "select p_timestamp from backend",
    "startTime": "2024-03-06T22:00:00+00:00",
    "endTime": "2024-03-06T22:02:00+00:00"
}
```

1. result:

```
[
    {
        "p_timestamp": "2024-03-06T22:01:59.998"
    },
    {
        "p_timestamp": "2024-03-06T22:01:59.953"
    },
    {
        "p_timestamp": "2024-03-06T22:01:59.897"
    },
    {
        "p_timestamp": "2024-03-06T22:01:59.852"
    },
    {
        "p_timestamp": "2024-03-06T22:01:59.797"
    },
    {
        "p_timestamp": "2024-03-06T22:01:59.753"
    },
    {
        "p_timestamp": "2024-03-06T22:01:59.698"
    },
    {
        "p_timestamp": "2024-03-06T22:01:59.652"
    },
    {
        "p_timestamp": "2024-03-06T22:01:59.598"
    },
    {
        "p_timestamp": "2024-03-06T22:01:59.552"
    },
    
    ...
    
    {
        "p_timestamp": "2024-03-06T22:01:00.478"
    },
    {
        "p_timestamp": "2024-03-06T22:01:00.464"
    },
    {
        "p_timestamp": "2024-03-06T22:01:00.378"
    },
    {
        "p_timestamp": "2024-03-06T22:01:00.364"
    },
    {
        "p_timestamp": "2024-03-06T22:01:00.279"
    },
    {
        "p_timestamp": "2024-03-06T22:01:00.264"
    },
    {
        "p_timestamp": "2024-03-06T22:01:00.178"
    },
    {
        "p_timestamp": "2024-03-06T22:01:00.164"
    },
    {
        "p_timestamp": "2024-03-06T22:01:00.080"
    },
    {
        "p_timestamp": "2024-03-06T22:01:00.065"
    }
]
```

**Comment by nitisht** [comment]
Thanks for the report @MinCrohn - how are you running Parseable? Is it in a container? Can you paste the output of `date` command from within the VM or container where Parseable is running?

**Comment by MinCrohn** [comment]
@nitisht  I used Postman to send the query to https://demo.parseable.com/api/v1/query.

<img width="1481" alt="demo-parseable-body-1" src="https://github.com/parseablehq/parseable/assets/48748249/4c939950-4f79-4575-8782-f55fede06741">
<img width="1481" alt="demo-parseable-body-2" src="https://github.com/parseablehq/parseable/assets/48748249/037a5168-f1fd-449b-9507-c3e0c5ef7a18">
