### ISSUE TITLE
Ability to configure CORS

### ISSUE THREAD

**Issue by jrabausch** [parseablehq/parseable#697]
Hello Parseable Team,

I am trying to use Parseable on my local machine to catch some logs of my frontend app.
Searching the docs, I could not find any options to configure CORS headers for the Parseable server, which prevents me from sending the logs directly via the browser's fetch api. 

Is there a way to get around that or do I have to use a local reverse proxy to add the headers?

Kind regards
Johannes

**Comment by nitisht** [comment]
Right now CORS is not configurable, but we can take a look @jrabausch . Thanks for reporting.
