### ISSUE TITLE
Unify and use a single S3 client 

### ISSUE THREAD

**Issue by nitisht** [parseablehq/parseable#70]
~Currently the server uses `aws-sdk-s3` while Datafusion has a dependency on `object-storage` crate that uses `rusoto`. We need to unify and use a single S3 client in both the places so there is lesser overhead in config / maintenance.~

Datafusion uses [object-store](https://crates.io/crates/object_store) which now has moved away from rusoto core. If the implementation is solid enough then we can use it for S3 and other object store. Other notable such crate is [openDAL](https://crates.io/crates/opendal).

List of related issues

- [ ] https://github.com/parseablehq/parseable/issues/296
- [ ] https://github.com/parseablehq/parseable/issues/284
- [ ] https://github.com/parseablehq/parseable/issues/270

**Comment by trueleo** [comment]
Datafusion uses [object-store](https://crates.io/crates/object_store) which now has moved away from `rusoto core`. If the implementation is solid enough then we can use it for S3 and other object store. Other notable such crate is [openDAL](https://crates.io/crates/opendal).

**Comment by nitisht** [comment]
can include #284 in this fix as well
