### ISSUE TITLE
Ingest 400 error

### ISSUE THREAD

**Issue by vrelk-net** [parseablehq/parseable#706]
I am having an issue where some streams are not ingested. I have 2 streams sent from syslog-ng on the host machine, so no reverse-proxy, using a user I have since promoted to editor, then admin (both roles at once). I had to create both streams manually. The first one "authelia" works fine, but the second "nginx" stream gets a 400 error code. If I delete the stream so it can create it itself, it returns a 404 instead.

I am unsure if this is related to issue #702 or not.

`[2024-03-18T12:26:24Z INFO  actix_web::middleware::logger] 172.17.0.1 "POST /api/v1/logstream/authelia HTTP/1.1" 200 0 "-" "syslog-ng User Agent" 0.005303`
`[2024-03-18T12:20:44Z INFO  actix_web::middleware::logger] 172.17.0.1 "POST /api/v1/logstream/nginx HTTP/1.1" 400 79 "-" "syslog-ng User Agent" 0.000138`
`[2024-03-18T12:22:44Z INFO  actix_web::middleware::logger] 172.17.0.1 "POST /api/v1/logstream/nginx HTTP/1.1" 404 22 "-" "syslog-ng User Agent" 0.000109`

**Comment by nitisht** [comment]
What is the version you're running here @vrelk-net ? #702 is related to distributed Parseable work that is going on in the `distributed` branch. It is not ready yet and we'd not recommend running the distributed branch code yet.

**Comment by nitisht** [comment]
any updates here @vrelk-net ?

**Comment by nitisht** [comment]
Closing due to no response, feel free to reopen if issue presists

**Comment by vrelk-net** [comment]
Sorry, I must have missed the notification emails. I followed the instructions at https://www.parseable.com/docs/installation/setup-parseable-on-docker.
I'm not sure of the version number as I moved on due to the issues that were preventing me from using it, but this would be the docker image available at the time would be https://hub.docker.com/layers/parseable/parseable/latest/images/sha256-b4da4a0bb05c89c0904901e8b38af4c3e171879f3c10b2aa7caa3416cbe262f4?context=explore

**Comment by vrelk-net** [comment]
@nitisht Sorry, I must have missed the notification emails. I followed the instructions at https://www.parseable.com/docs/installation/setup-parseable-on-docker.
I'm not sure of the version number as I moved on due to the issues that were preventing me from using it, but this would be the docker image available at the time would be https://hub.docker.com/layers/parseable/parseable/latest/images/sha256-b4da4a0bb05c89c0904901e8b38af4c3e171879f3c10b2aa7caa3416cbe262f4?context=explore

**Comment by nitisht** [comment]
I see, do you mind trying with the `edge` image tag once? We'll meanwhile try with the syslog setup.

**Comment by vrelk-net** [comment]
After messing with it a bit on `edge`, I haven't run into any issues.

**Comment by nitisht** [comment]
Great to know. We'll close this then for now. Feel free to let us know if anything comes up
