### ISSUE TITLE
unable to change p_timestamp‘s timezone

### ISSUE THREAD

**Issue by f1ynng8** [parseablehq/parseable#714]
I deploy parseable using Docker container. 
Is the p_timestamp's value associated with the container's Time Zone setting?

I have set the environment of "- TZ=Asia/Shanghai", but p_timestamp's value is still in UTC time.

**Comment by nitisht** [comment]
`p_timestamp` is an internal field, meant for Parseable's usage. We don't support changing the `p_timestamp` at all - why do you want to change it?

**Comment by f1ynng8** [comment]
> `p_timestamp` is an internal field, meant for Parseable's usage. We don't support changing the `p_timestamp` at all - why do you want to change it?

Thank you for the explanation. I thought user can change `p_timestamp` displaying while keeping its original value internally. Anyway, I thinkI should add an user defined timestamp field with the desired time zone.
