### ISSUE TITLE
Grafana Dashboard Demo Login doesn't work

### ISSUE THREAD

**Issue by thinkORo** [parseablehq/parseable#759]
I want to give the Parsaeble Grafana Plugin a try. In the documentation I can find a link to a demo server: https://www.parseable.com/docs/integrations/grafana-data-source-configuration#sample-dashboard

Unfortunatey I cannot login with any possible credentials. I tried:
- user: admin, password: admin
- user: admin, password: parseable
- user: parseable, password: parseable

So, what's the correct credential for this demo? In the documentation of the Grafana Parseable Plugin it's parseable/parseable. But, as mentioned, this doesn't work for me.

**Comment by nitisht** [comment]
Let me get back on this shortly @thinkORo

**Comment by nitisht** [comment]
hey @thinkORo please use 

http://demo.parseable.com:3000/
admin, admin123

**Comment by nitisht** [comment]
we'll fix the docs as well shortly. Closing this issue as fixed
