### ISSUE TITLE
Feat: The log rotation policy requires a file size limit

### ISSUE THREAD

**Issue by sp0cket** [parseablehq/parseable#797]
There may be situations where the size of logs cannot be predicted. For example, if a bug causes an abnormal amount of logs to be generated, it could fill up the disk and crash the system. A protection mechanism is needed to limit the maximum file size and delete old logs when the file becomes too large.

**Comment by nitisht** [comment]
Thanks @sp0cket . We can mitigate this by allowing the log retention to work on files sizes also instead of days only.

**Comment by sp0cket** [comment]
I think both limits may be needed, and both may need to be cleaned up when either limit is reached.
