### ISSUE TITLE
Unreachable code panic

### ISSUE THREAD

**Issue by moenodedev** [parseablehq/parseable#817]
While evaluating parseable for a day we encountered a panic. The service stopped accepting log events. After deleting the and recreating the stream the service was able to accept log events again.

Parseable v1.2.0

```
Jun 11 16:34:25 thread 'actix-rt|system:0|arbiter:0' panicked at server/src/event/format/json.rs:224:14:
Jun 11 16:34:25 internal error: entered unreachable code
```

The full backtrace is attached.

[backtrace.log](https://github.com/user-attachments/files/15792573/backtrace.log)

**Comment by nitisht** [comment]
Thanks @moenodedev , we'll take a look shortly. Can you also help us understand details of this deployment - server specs, load on the server, agent / application used to send logs etc.

**Comment by moenodedev** [comment]
Thanks for looking into the panic. The aarch64 EC2 instance has low CPU and RAM usage. We're sending logs through the API over HTTP with curl and ruby.

We tried resending a request that was previously accepted but received an SSL error.
```
SSL_read: unexpected eof while reading (OpenSSL::SSL::SSLError)
```

All log messages have a data field. Most of the events contain a hash but sometimes it's a string. Could the schema difference be the problem?

**Comment by moenodedev** [comment]
The panic could be caused by `X-P-Meta-user_id` or `user_id` in the request body being null sometimes.

**Comment by nikhilsinhaparseable** [comment]
@moenodedev please let us know the version you are running. We can then analyse the issue.

**Comment by moenodedev** [comment]
We stopped our trial of parseable because there were many types of panics with basic usage to local-store.

**Comment by moenodedev** [comment]
The most recent panic was:
```
Jun 14 23:06:05 thread '<unnamed>' panicked at server/src/storage/object_storage.rs:544:85:
Jun 14 23:06:05 called `Result::unwrap()` on an `Err` value: Parquet error: Invalid Parquet file. Size is smaller than footer
```

**Comment by moenodedev** [comment]
Either tags or metadata were causing problems. After removing those headers most of the panics stopped.

**Comment by nitisht** [comment]
@moenodedev I see the last comment about tags / headers now deleted - I guess you're still seeing issue. We would really like to figure this out and fix this. 

Do you mind joining us on Slack : https://logg.ing/community so we can collaborate better. If not we can even do a short call so we can review the deployment: https://logg.ing/quick-chat . Either ways. we'd love to understand the workflow here and the setup to see what is going on. Because in our testing we've not seen this yet.

**Comment by moenodedev** [comment]
We deleted our test instance because there were many panics and freezes and many of the docs are out of date. Another freeze was caused by a dynamic schema first receiving a value that was an integer then later receiving a string.

**Comment by nitisht** [comment]
@moenodedev there are 100s of live deployments of Parseable - running without any such issues reported. Hence I was very keen to understand what is happening here and how we can fix this for you. Since you don't want to pursue this, we'll try to repro this ourselves. Thank you for reporting.
