### ISSUE TITLE
Using Arrow Flight Protocol for Querying: Missing documentation?

### ISSUE THREAD

**Issue by thinkORo** [parseablehq/parseable#820]
Hi there,

with #769 the Arrow Flight Protocol was implemented and is published with release 1.2.

But I cannot find any (minimum) documentation how to connect to the new Arrow Flight endpoint.

What did I do?

1. I set the environment P_FLIGHT_PORT to 8002
2. I tried to connect to mymachine:8002 via:

- Arrow Flight JDBC driver
- adbc_driver_flightsql
- pyarrow.flight

But for all tests I get the following more or less same error:

**adbc_driver_flightsql**
`NotSupportedError: NOT_IMPLEMENTED: [FlightSQL] handshake is disabled in favour of direct authentication and authorization (Unimplemented; AuthenticateBasicToken)`

**pyarrow.flight**
`ArrowNotImplementedError: Flight returned unimplemented error, with message: handshake is disabled in favour of direct authentication and authorization`

Could you please provide any example or documentation how to connect to Arrow Flight endpoint either via JDBC or via Python?

**Comment by nitisht** [comment]
Thanks @thinkORo we're working on the the documentation for this. We'll also release sample applications in Js and Python to use this API. Will be available soon. 

Also, in the next release the Parseable console will use this API for querying, improving the UX.

**Comment by thinkORo** [comment]
@nitisht Thanks for your quick reply. I'm looking forward checking some examples or reading the documentation.

**Comment by nikhilsinhaparseable** [comment]
@thinkORo below is the blog where you can find the details for arrow flight in Parseable
https://www.parseable.com/blog/optimize-data-transfer-with-parseable

**Comment by nikhilsinhaparseable** [comment]
@thinkORo the reason is - release is not done yet, you can expect the release by next week which will have this fix.
Regarding the Authorization header, you need to send as Basic <Base64 encoded string of username:password>

**Comment by thinkORo** [comment]
Okay, I'll check that later. And yes, regarding  Authorization header: that's what I did as well. Thanks for your quick reply.

**Comment by nitisht** [comment]
@thinkORo meanwhile you can try the `edge` tag from our Docker images, e.g. `parseable/parseable:edge` - this image always points to latest main branch commit.

**Comment by thinkORo** [comment]
Hi @nikhilsinhaparseable, sorry, I didn't find the time to check the edge-image. But now I do. It is working as expected. The request does not "feel" as if it is executed immediately, but I receive the requested data and can work with it. Super. Many thanks for pointing out the edge image. I really appreciate it.
