### ISSUE TITLE
Suggested UI improvements 

### ISSUE THREAD

**Issue by tweeter0830** [parseablehq/parseable#827]
Hey all! Thanks for all the great work on parseable. I’m trying to use it. The UI lacks a few features which are limiting the utility for me.

1. It would be really nice to be able to supply a query for the “explore” page via a url parameter or something. I’m launching multiple batch jobs per stream and need to show a user only the rows for their job.
2. Newline characters should be respected in the ui. These don’t work in parseable today as the tables will be flattened to a single line
3. There should be some way to adjust the real estate each column gets. Right now, a column can dominate the UI. For example, if I log a single really long message, the “message” column will dominate the screen and I’ll need to scroll right/left to view the other columns

**Comment by balaji-jr** [comment]
> Hey all! Thanks for all the great work on parseable. I’m trying to use it. The UI lacks a few features which are limiting the utility for me.
> 
> 1. It would be really nice to be able to supply a query for the “explore” page via a url parameter or something. I’m launching multiple batch jobs per stream and need to show a user only the rows for their job.
> 2. Newline characters should be respected in the ui. These don’t work in parseable today as the tables will be flattened to a single line
> 3. There should be some way to adjust the real estate each column gets. Right now, a column can dominate the UI. For example, if I log a single really long message, the “message” column will dominate the screen and I’ll need to scroll right/left to view the other columns

Thanks @tweeter0830 for your valuable input. We will include these updates in the upcoming releases on https://github.com/parseablehq/console

**Comment by balaji-jr** [comment]
@tweeter0830 
We have now added support for preserving newline characters in strings. Regarding the first point, until we implement URL context, which will allow the app to retain context through URL parameters, you can use saved filters that support saving a fixed time range. We are also working on making table cell widths adjustable.

**Comment by balaji-jr** [comment]
@tweeter0830 
With the release of version 1.5.4, we've included support for adjusting specific column widths and toggling word wrap. We’ll also address the reduction of app context from query parameters in this [issue](https://github.com/parseablehq/console/issues/146). Closing this for now—thank you!
