### ISSUE TITLE
Support for GCS (Google Cloud Storage)

### ISSUE THREAD

**Issue by adarshsrivastava11** [parseablehq/parseable#842]
Hi, I'm trying to run Parseable on my GCP cloud, but I am not able to connect with my GCS bucket. Getting the following error - 
<img width="766" alt="Screenshot 2024-07-08 at 6 35 06 PM" src="https://github.com/parseablehq/parseable/assets/14872767/d8858e47-cf9e-49a1-a4da-de26894e3e02">

This is my `env` file - 
```
P_STAGING_DIR=/staging
P_ADDR=0.0.0.0:8000
P_USERNAME=admin
P_PASSWORD=admin
P_S3_URL=https://storage.googleapis.com
P_S3_BUCKET=gcs://testing
P_S3_REGION=asia-south1
```

**Comment by nitisht** [comment]
thanks for reporting @adarshsrivastava11 . Can you set `P_S3_BUCKET=testing` and also ensure S3 Compatibility is set in the GCS console?

**Comment by nitisht** [comment]
This is testing and is working @adarshsrivastava11 Closing this for now. Feel free to reopen if you see something not working as expected.
