### ISSUE TITLE
Search on https://www.parseable.com/docs/ does not work

### ISSUE THREAD

**Issue by olexiyb** [parseablehq/parseable#858]
Now sure if this is right repository but search does not work on [docs](https://www.parseable.com/docs/)

<img width="1305" alt="image" src="https://github.com/user-attachments/assets/cc548ff8-ada0-4496-aa3c-24aaa142e93a">

**Comment by nitisht** [comment]
Thanks for reporting @olexiyb , we'll take a look. Looks like Algolia (that we use for search) hasn't indexed the whole website properly. We'll sort this out.

**Comment by nitisht** [comment]
@olexiyb this is fixed now in https://www.parseable.com/docs
