### ISSUE TITLE
Helm: Missing `emptyDir` mount in querier StatefulSet in HA mode

### ISSUE THREAD

**Issue by bastjan** [parseablehq/parseable#880]
Helm release `v1.4.0` moved the Querier from a Deployment to a StatefulSet.

The old deployment mounted an empty dir to `/parseable/staging`: https://github.com/parseablehq/parseable/blob/245aa8b6214cab293b3f685e5394d5f0f804f66e/helm/templates/querier-deployment.yaml#L70-L71

This was removed from the new STS and thus on systems with `readOnlyRootFilesystem` set, the querier crashes on startup with a rather obscure error message:

```
Error: IO Error: Permission denied (os error 13)

Caused by:
Permission denied (os error 13)
```

## Affected versions

Helm release `v1.4.0`

**Comment by nitisht** [comment]
thanks for flagging this one @bastjan I'll fix this asap.
