### ISSUE TITLE
Expose additional fields in Helm chart

### ISSUE THREAD

**Issue by sebzimmermann** [parseablehq/parseable#896]
To make the Helm chart more useable in production environments, additional fields should be exposed via `values.yaml`.

1) `sidecars`: It should be possible to add sidecars to the pods, specifically to the `querier-service`. A use-case would be to add e.g. a caddy sidecar to easily expose the service to the public network (e.g. tailscale vpn).
2) `labels`: It should be possible to add custom labels (like `podAnnotations`) to the pods. Labels are often used by other services to identify a specific services and its settings (e.g. a version-checker).
3) `volumes`: It should be possible to add additional volumes to a pod. These volumes might be used by sidecars/other containers.

**Comment by nitisht** [comment]
Thanks @sebzimmermann we'll pick this up shortly
