### ISSUE TITLE
100% CPU utilization while idle

### ISSUE THREAD

**Issue by 123vivekr** [parseablehq/parseable#90]
I've noticed the program uses 100% of one of the 4 CPU threads while idling without any tasks. This seems like a bug which needs to be looked into.

**Comment by trueleo** [comment]
Can confirm this is an issue ( persists when running server with more workers ). I'll try to profile parseable to see what is causing this but most of code is async and thus idle correctly. The noticable culprit could be spin loop check on localsync which runs the schedular.

![Screenshot_20220904_113239](https://user-images.githubusercontent.com/29176136/188299801-c2dc24c4-bf90-4e7d-add8-2b008e062b8b.png)

In addition to this opening two more issues related to resource utilization/
