### ISSUE TITLE
Stream names should be less restrictive

### ISSUE THREAD

**Issue by sebzimmermann** [parseablehq/parseable#917]
As the stream names are coupled with s3 prefixes, they should also be aligned in terms of naming conventions (at the moment only lower case alphanumeric characters are allowed). 

The target should be to also allow "Safe characters" listed in the aws docs: 
https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html

**Comment by nikhilsinhaparseable** [comment]
Hi @sebzimmermann as per the doc, below is the list of allowed special characters -

Exclamation point (!)
Hyphen (-)
Underscore (_)
Period (.)
Asterisk (*)
Single quote (')
Open parenthesis (()
Close parenthesis ())

Ingestion works well to S3 but in the query api, we have to wrap the table name in double quotes for datafusion to understand these prefixes in S3 to find data,
say, i create a stream with a name `a.b`, we will have to send this query to datafusion -
`"select * from \"a.b\""`

IMO other than below special chars -
Hyphen (-)
Underscore (_)
Period (.)
nothing else make sense in the stream/table name 

please provide your opinion on this.

Thanks!
