### ISSUE TITLE
Support encryption on object storage

### ISSUE THREAD

**Issue by udf2457** [parseablehq/parseable#919]
Is there a technical reason for the omission of encryption on object storage (S3) ?

This could be done even without introducing any extra code to `parseable` if you exposed support for S3-side features such as [SSE-C](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html).

**Comment by nitisht** [comment]
Can you elaborate a bit.

> if you exposed support for S3-side features such as [SSE-C](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html).

What do we have to expose here?

**Comment by udf2457** [comment]
> What do we have to expose here?

Basically all you need to do is introduce the extra env-vars and push that down to your S3 code so the correct HTTP headers are set.

For example, enabling SSE-C is as simple as sending the following headers when interacting with S3:

`x-amz-server-side​-encryption​-customer-algorithm`: currently a fixed static value, `AES256`
`x-amz-server-side​-encryption​-customer-key`: 256-bit, base64-encoded encryption key
`x-amz-server-side​-encryption​-customer-key-MD5`: base64-encoded 128-bit MD5 digest of the encryption key

**Comment by nitisht** [comment]
I see, this is useful @udf2457 . We'll take a look soon.

**Comment by udf2457** [comment]
No problem.

People who use the AWS native S3 might point out they can configure encryption via AWS S3 management (e.g. if you are 100% AWS-ecosystem you can configure so a bucket uses AWS KMS hosted keys).

So this feature is perhaps of most significant interest to those (like me 😉 ) who use S3-compatible services from other non-AWS providers or software (e.g. `minio`).

**Comment by lazyfuhrer** [comment]
I want to work on this. Can I be assigned ? @nitisht

**Comment by nitisht** [comment]
Sure @lazyfuhrer please go ahead.
