### ISSUE TITLE
Feat: Add native Kafka integration for Parseable server

### ISSUE THREAD

**Issue by nitisht** [parseablehq/parseable#936]
User should be able to set environment variables to integrate their Kafka cluster with Parseable. 

- Decide which env vars are needed for this integration.
- Use a Rust Kafka client like https://github.com/kafka-rust/kafka-rust to subscribe to events from the Kafka client.
- Ingest data from the given Kafka topic.
- Once events are ingested, merge the binary data from Kafka to the Parseable data ingestion flow.

**Comment by onyedikachi-david** [comment]
/attempt #936

@nitisht: Is this task available for assignment? If not, are you accepting open contributions with the best submission to be selected?
