### ISSUE TITLE
Login: 400 Bad request

### ISSUE THREAD

**Issue by dhenry123** [parseablehq/parseable#942]
Hi,
From 1.5.0, impossible to update to 1.5.1, on login, i got a response 400 bad request, tried to upgrade 1.5.0=>1.5.2 the same.
Platform is arm64 with binary package. The ingest process works

Best regards

**Comment by nitisht** [comment]
What is the user here? Are you logging in as admin?

**Comment by dhenry123** [comment]
yes and also tried changing env var (P_USERNAME && P_PASSWORD) at start, and i loosed my reports when i rolled back to 1.5.0 (not really a problem for my case).

**Comment by nikhilsinhaparseable** [comment]
can you please open the network tab and check the API request and error response when you try login

**Comment by balaji-jr** [comment]
In addition to that,
1. Can you also post the failed /login network request URL as well (to verify the redirect URL which has been sent as query params)
2. Or you can try removing the env vars completely and logging in with the default username and password `admin` & `admin`
3. Would it be possible to check the .parseable.json where all the users' details have been saved? 
Could you verify that the user you are trying to log in exists?

**Comment by dhenry123** [comment]
i load the login page, set admin/admin (appears in the logs server) and click on the login button, ui send only one request https://[mydomain/api/v1/o/login?redirect=https://[mydomain] response is 400 Bad Request

I m behind a reverse proxy in charge to proceed httpS which works well with 1.5.0

**Comment by dhenry123** [comment]
i ve just to restart the process after removing all data including .users .parseable, server start normally but impossible to log in with admin/admin as displayed in the log server i tried to use sso same response

**Comment by wendellrocha** [comment]
I'm experiencing the same issue. I'm behind an Nginx Proxy Manager instance using Cloudflare tunnels to expose it to the internet.
![CleanShot 2024-09-26 at 08 23 46](https://github.com/user-attachments/assets/fd84dd5e-e0bc-42bf-91ac-5deacbd98856)

Accessing by the IP, over HTTP works.
![CleanShot 2024-09-26 at 08 27 46](https://github.com/user-attachments/assets/51af2a8f-dabf-4ab4-bda3-95fc96ee9f1e)

**Comment by balaji-jr** [comment]
Ty. @wendellrocha
This helps. We will fix this shortly.
