### ISSUE TITLE
Download not working (curl -fsSL https://logg.ing/install | bash)

### ISSUE THREAD

**Issue by bobmcallan** [parseablehq/parseable#959]
There doe snot appear to be any binaries available @ cdn.parseable.com?

Is the script still valid?

Bob

**Comment by nitisht** [comment]
Hi @bobmcallan yes, the script is valid. I think we missed updating the latest release on the CDN endpoint. Let me fix that in a bit. Will let you know here once done.

**Comment by nitisht** [comment]
Hi @bobmcallan this is fixed now. I just verified it works for me. Can you confirm you're able to download now?

**Comment by bobmcallan** [comment]
Looks good, download works. Thanks

**Comment by bobmcallan** [comment]
Closing.
